package com.stackroute.knowledgevault.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Input Data object generated by Extractor-Service.
 */

@Data
@AllArgsConstructor
public class ExtractedFileData {

    private static Integer count = 0;

    private Integer id;
    private String metadata;
    private String content;

    public ExtractedFileData() {
        this.id = count++;
    }
}
